import Link from "next/link";
import { ArrowRight } from "lucide-react";
import { createPageMetadata } from "@/lib/seo";
import { ClosingCTA, PageHero } from "@/components/marketing";
import { Header } from "@/components/site";
import { Footer, Label } from "@/components/site-content";
import { Button } from "@/components/ui/button";

export const metadata = createPageMetadata({
  title: "Management Reporting & Custom Dashboards | Auxilee",
  description: "Custom management reports and dashboards that bring financial, project, property, and operational KPIs together for better business decisions.",
  path: "/management-reporting",
});

const metricGroups = [
  { title: "Financial Performance", items: ["Revenue", "Gross profit & gross margin", "Net profit", "Cash flow", "Accounts receivable", "Budget vs. actual", "Overhead", "Payroll & labor costs"] },
  { title: "Construction & Project Performance", items: ["Project profitability", "Estimated vs. actual costs", "Gross margin by project", "Work in progress (WIP)", "Margin fade", "Backlog", "Change orders", "Retainage"] },
  { title: "Real Estate & Flipping", items: ["Property or project profitability", "Acquisition cost", "Rehab budget vs. actual", "Holding costs", "Days held", "Cash flow by property", "Performance by entity", "Portfolio performance"] },
  { title: "Sales & Marketing", items: ["Lead volume", "Cost per lead", "Cost per acquisition", "Cost per deal", "Conversion rate", "Revenue by lead source", "Sales pipeline"] },
] as const;

export default function ManagementReporting() {
  return <main className="overflow-hidden bg-background text-foreground">
    <Header />
    <PageHero label="Management reporting & custom dashboards" title="See the Numbers That Matter Most to Your Business." copy="Standard financial statements only tell you so much. Auxilee builds custom management reports and dashboards around the financial and operational numbers you actually use to run your business. See the numbers that drive your business — so you can make better decisions, faster." image="/assets/auxilee-bookkeeping-hero.webp" alt="Business owner reviewing financial reports" />

    <section className="px-5 py-24 md:px-10 md:py-32 lg:px-16"><div className="mx-auto grid max-w-[1280px] gap-12 lg:grid-cols-[.85fr_1.15fr] lg:gap-20"><div><Label>Beyond statements</Label><h2 className="font-display text-4xl leading-tight md:text-5xl">Your Financial Statements Only Tell Part of the Story.</h2></div><div className="space-y-6 text-lg leading-8 text-muted-foreground"><p>Your P&amp;L, balance sheet and cash flow statement are important. But they don’t always answer the questions you have as an owner.</p><p className="border-l-2 border-action pl-6 font-display text-xl leading-snug text-foreground">Which projects are actually making money? Are margins improving or shrinking? What does it cost to acquire a new customer? Which properties are performing best? How much work do we have in the pipeline?</p><p>Management reporting brings the numbers you care about together so you can see what’s happening without digging through financial statements, spreadsheets and different systems to find the answer.</p></div></div></section>

    <section className="bg-primary px-5 py-24 text-primary-foreground md:px-10 md:py-32 lg:px-16"><div className="mx-auto max-w-[1280px]"><Label dark>Better visibility</Label><h2 className="max-w-4xl font-display text-4xl leading-tight md:text-6xl">Better Visibility. Better Decisions.</h2><p className="mt-5 font-display text-2xl">The Numbers You Need — In One Place.</p><div className="mt-8 max-w-4xl space-y-6 text-lg leading-8 text-primary-foreground/70"><p>A management dashboard gives you a clear view of the key performance indicators that matter most to your business. Instead of waiting until something shows up on a financial statement months later, you can track performance over time, identify trends and see where something may need your attention.</p><p>And the numbers don’t have to be purely financial. We can combine financial, operational, project, property, sales and marketing metrics to give you a more complete picture of how the business is performing.</p><p className="font-display text-2xl text-primary-foreground">The goal isn’t more reports. It’s better information for making decisions.</p></div></div></section>

    <section className="px-5 py-24 md:px-10 md:py-32 lg:px-16"><div className="mx-auto max-w-[1280px]"><Label>What you could track</Label><h2 className="max-w-3xl font-display text-4xl leading-tight md:text-6xl">What Could You Track?</h2><p className="mt-6 max-w-3xl text-lg leading-8 text-muted-foreground">Every business is different, but here are some of the reports, metrics and KPIs we can help clients see more clearly:</p><div className="mt-14 grid gap-px border border-border bg-border md:grid-cols-2">{metricGroups.map(group => <article key={group.title} className="bg-card p-7 md:p-9"><h3 className="font-display text-2xl">{group.title}</h3><ul className="mt-6 grid gap-3 sm:grid-cols-2">{group.items.map(item => <li key={item} className="flex gap-3 leading-6 text-muted-foreground"><span className="text-action" aria-hidden="true">→</span>{item}</li>)}</ul></article>)}</div><p className="mt-10 max-w-3xl font-display text-xl leading-snug">These are examples — not a fixed menu. If there’s a number you need to run your business, let’s talk about how to track it.</p><div className="mt-8"><Button asChild variant="action" size="callout"><Link href="/contact">Talk With Our Team <ArrowRight className="text-primary" /></Link></Button></div></div></section>

    <section className="bg-card px-5 py-24 md:px-10 md:py-32 lg:px-16"><div className="mx-auto grid max-w-[1280px] gap-12 lg:grid-cols-[.8fr_1.2fr] lg:gap-20"><div><Label>Built for your business</Label><h2 className="font-display text-4xl leading-tight md:text-5xl">Built Around Your Business — Not Ours.</h2><p className="mt-5 font-display text-2xl">You Tell Us What You Want to Know.</p></div><div className="space-y-6 text-lg leading-8 text-muted-foreground"><p>Maybe you want a simple monthly report showing project profitability. Maybe you need to see performance across multiple properties or entities. Or maybe you want one dashboard that combines financial performance, operations, projects and marketing.</p><p>We start with the questions you want answered, then determine the numbers and information that will help answer them. From there, we can create reporting around the KPIs, projects, properties, entities and time periods that matter to you.</p><p>Your reporting might be a straightforward monthly management report, a more detailed reporting package or a visual dashboard that gives you the big picture at a glance.</p><p className="font-medium text-foreground">And if you’re not sure what you should be tracking, we can help with that, too.</p></div></div></section>

    <section className="px-5 py-24 md:px-10 md:py-32 lg:px-16"><div className="mx-auto grid max-w-[1280px] gap-12 lg:grid-cols-[.8fr_1.2fr] lg:gap-20"><div><Label>More than bookkeeping</Label><h2 className="font-display text-4xl leading-tight md:text-5xl">More Than Bookkeeping.</h2><p className="mt-5 font-display text-2xl leading-snug">Good Books Tell You What Happened. Good Reporting Helps You Decide What to Do Next.</p></div><div className="space-y-6 text-lg leading-8 text-muted-foreground"><p>Accurate bookkeeping is the foundation, but keeping the books is only part of how Auxilee can support your business.</p><p>We want our clients to understand their numbers and have the visibility they need to make better decisions. Management reporting turns the financial and operational information already being generated by your business into something more useful — so you can see where you’re making money, where things are changing and what deserves your attention.</p><p className="font-medium text-foreground">We see ourselves as a partner in your business — not simply the company keeping your books.</p></div></div></section>

    <ClosingCTA title="What Do You Want to Know About Your Business?" line="Tell us what you wish you could see more clearly. We’ll help you determine what to track and build the reporting around it." />
    <Footer />
  </main>;
}
